Revert "Dispatch Tugboat API calls on main branch (#1483)"
This reverts commit 642775ff6e1e03435dfb98c73ce185c28298579a.

diff --git a/.github/workflows/tugboat-pr-updated.yml b/.github/workflows/tugboat-pr-updated.yml
--- a/.github/workflows/tugboat-pr-updated.yml
+++ b/.github/workflows/tugboat-pr-updated.yml
@@ -8,21 +8,32 @@ on:
 
 jobs:
   tugboat_rebuild_preview:
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
+    env:
+      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
     name: Rebuild Tugboat Preview
     steps:
-    - name: Dispatch Tugboat Preview Rebuild
-      continue-on-error: true
-      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
+    - name: Restore Preview ID
+      uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
       with:
-        script: |
-          await github.rest.actions.createWorkflowDispatch({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            workflow_id: 'tugboat-dispatch.yml',
-            ref: 'main',
-            inputs: {
-              action: 'rebuild',
-              pr_number: ${{ github.event.pull_request.number }},
-            }
-          });
+        path: .tugboat_preview.txt
+        key: ${{ runner.os }}-tugboat-preview-id-pr-${{ github.event.pull_request.number }}
+    - name: Set Preview ID
+      run: |
+        if ! [ -f .tugboat_preview.txt ]; then
+          echo "Preview ID not found, please manually rebuild Tugboat Preview. Contact platform-cms-qa on Github or CMS QA Engineers in #cms-support on Slack for assistance."
+          exit 1
+        fi
+        PREVIEW_ID=$(cat .tugboat_preview.txt)
+        echo "Preview ID: ${PREVIEW_ID}"
+        echo "PREVIEW_ID=$PREVIEW_ID" >> $GITHUB_ENV
+    - name: Cleanup temporary file
+      run: rm .tugboat_preview.txt
+    - name: Rebuild Tugboat Preview
+      run: |
+        curl --fail \
+          -H "Authorization: Bearer ${{ secrets.TUGBOAT_API_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          -X POST \
+          -d '{ "children": "false", "force": "false" }' \
+          https://api.tugboat.vfs.va.gov/v3/previews/${{ env.PREVIEW_ID }}/rebuild
