Exit with error if preview ID not found

diff --git a/.github/workflows/tugboat-pr-closed.yml b/.github/workflows/tugboat-pr-closed.yml
--- a/.github/workflows/tugboat-pr-closed.yml
+++ b/.github/workflows/tugboat-pr-closed.yml
@@ -17,8 +17,13 @@ jobs:
     - name: Set Preview ID
       run: |
         PREVIEW_ID=$(cat .tugboat_preview.txt)
-        echo $PREVIEW_ID
-        echo "PREVIEW_ID=$PREVIEW_ID" >> $GITHUB_ENV
+        if [ -z "$PREVIEW_ID" ]; then
+          echo "Preview ID not found, please manually delete Tugboat Preview."
+          exit 1
+        else
+          echo $PREVIEW_ID
+          echo "PREVIEW_ID=$PREVIEW_ID" >> $GITHUB_ENV
+        fi
     - name: Delete Tugboat Preview
       run: |
         curl -H "Authorization: Bearer ${{ secrets.TUGBOAT_API_TOKEN }}" \
